name: Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Github Actions - Release'
        required: true
        default: 'Github Actions - Release'

jobs:

  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Grant Permission
        run: sudo chmod +x ./mvnw

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '11'

      - name: Build and test
        run: mvn -ntp -B clean install

      - name: Install GPG
        run: |
            sudo apt-get update
            sudo apt-get install gnupg2 -qy

      - name: Maven Settings
      - uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: |
            [{
              "id": "ossrh",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_PASSWORD }}"
            }]

      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: echo "$GPG_PRIVATE_KEY" | gpg --import

      - name: Publish to Maven Central
        env:
            GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
            GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn -ntp -B deploy -Dgpg.keyname=${GPG_KEY_NAME} -Dgpg.passphrase=${GPG_PASSPHRASE}
